language: swift
osx_image: xcode12.1

cache: carthage

before_install:
   - ./carthage.sh update --cache-builds --platform iOS

script:
  - xcodebuild test -project TravisTest.xcodeproj -scheme TravisTestTests -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.1'
